spring:
  application:
    name:
      G-Learn-E

  profiles:
    active:
      prod

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      show_sql: true
      format_sql: true
    open-in-view: false


jwt:
  secret: ${jwt.secret}
  expiration-time:
    email-auth-token: ${jwt.expiration-time.email-auth-token}
    access-token: ${jwt.expiration-time.access-token}
    refresh-token: ${jwt.expiration-time.refresh-token}




#  @Value("${jwt.secret}") String secretKey,
#  @Value("${jwt.expiration-time.access-token}") long accessTokenExpiration,
#  @Value("${jwt.expiration-time.refresh-token}") long refreshTokenExpiration