spring:
  application:
    name:
      G-Learn-E

  profiles:
    active:
      prod

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      show_sql: true
      format_sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust:
              smtp.gmail.com
            protocols:
              TLSv1.2


jwt:
  secret: ${jwt.secret}
  expiration-time:
    email-auth-token: ${jwt.expiration-time.email-auth-token}
    access-token: ${jwt.expiration-time.access-token}
    refresh-token: ${jwt.expiration-time.refresh-token}


mail-auth:
  code:
    expiration-time: ${mail-auth.code.expiration-time}
    length: ${mail-auth.code.length}
  allowed-domain:
    - gnu.ac.kr
    - gmail.com


security:
  path:
    permit-all:
      - "/swagger-ui/**"
      - "/v3/api-docs/**"
    #      - "/api/user/**"
    #      - "/api/map/**"
    authenticated:
      - "/api/auth/tokenRefresh"
      - "/api/auth/logout"
    #      - "/api/user"
    #      - "/api/certificates/**"
    #      - "/api/user/**"
    #      - "/api/building/**"
    #      - "/api/review/**"
    #      - "/api/notification/**"
    anonymous:
      - "/api/auth"
      - "/api/auth/login"
      - "/api/auth/email-auth/**"
    email-auth:
        - "/api/auth/signup"
    any-request: "permit-all"  # 'authenticated', 'permit-all', 'anonymous' 중 하나

fast-api:
  base-url: ${fast-api.base-url}
  endpoints:
    create-problem:
      method: ${fast-api.endpoints.create-problem.method}
      path: ${fast-api.endpoints.create-problem.path}
    grade-descriptive:
      method: ${fast-api.endpoints.grade-descriptive.method}
      path: ${fast-api.endpoints.grade-descriptive.path}
    grade-blank:
      method: ${fast-api.endpoints.grade-blank.method}
      path: ${fast-api.endpoints.grade-blank.path}
    daily-stats: # 사용량 조회
      method: ${fast-api.endpoints.daily-stats.method}
      path: ${fast-api.endpoints.daily-stats.path}
    daily-usage: # 로그 조회
      method: ${fast-api.endpoints.daily-usage.method}
      path: ${fast-api.endpoints.daily-usage.path}
    weekly-stats:
      method: ${fast-api.endpoints.weekly-stats.method}
      path: ${fast-api.endpoints.weekly-stats.path}
    weekly-usage:
      method: ${fast-api.endpoints.weekly-usage.method}
      path: ${fast-api.endpoints.weekly-usage.path}
    monthly-stats:
      method: ${fast-api.endpoints.monthly-stats.method}
      path: ${fast-api.endpoints.monthly-stats.path}
    monthly-usage:
      method: ${fast-api.endpoints.monthly-usage.method}
      path: ${fast-api.endpoints.monthly-usage.path}