name: CI/CD - BE
on:
  push: { branches: [ "main" ] }
  workflow_dispatch:

jobs:
  build-push:
    uses: GNU-CapstoneDesign-II/.github/.github/workflows/build-push.yml@main
    with:
      image_name: ${{ vars.DOCKERHUB_USERNAME }}/g-learn-e-be
      context: .
      dockerfile: ./DockerFile
    secrets: inherit

  deploy:
    needs: build-push
    uses: <ORG>/.github/.github/workflows/deploy-stack.yml@main
    with:
      image_app_ai: ${{ vars.DOCKERHUB_USERNAME }}/g-learn-e-ai
      image_app_be: ${{ vars.DOCKERHUB_USERNAME }}/g-learn-e-be
      stack_dir: $HOME/stack
    secrets: inherit
